example:
  property: I AM A DEFAULT PROPERTY OVERRIDE
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8
    username: root
    password: '{cipher}eba55edb5a21485c8689074009b6c430a572b7d92dc1cee2f9f1bdf38ca42b78'
